name: flutter_simple_app
description: A new Flutter project from Evgeny Abdullaev.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  analyzer: ^1.7.1
  cached_network_image: ^3.1.0
  flutter_svg: ^0.22.0
  json_annotation: ^4.0.0
  chopper: ^4.0.1
  logging: ^1.0.1
  provider: ^5.0.0
  equatable: ^2.0.3

  moor_flutter: ^4.0.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.2
  path: ^1.8.0

  google_fonts: ^2.1.0
  flutter_native_splash: ^1.2.1
  webview_flutter: ^2.0.12
  crypto: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.0
  json_serializable: ^4.1.3
  chopper_generator: ^4.0.1
  moor_generator: ^4.4.1

  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
